use std::io::Write;

use anyhow::Result;

use crate::model::{Entities, Grid, Tileset};

pub fn emit(
    grid: &Grid,
    entities: &Entities,
    tileset: &Tileset,
    mut out: impl Write,
) -> Result<()> {
    // Group by tile_type for batching, but in Unity we'll just instantiate prefabs.
    let mut tiles_by_type: std::collections::BTreeMap<&str, Vec<(f32, f32, f32)>> =
        std::collections::BTreeMap::new();
    for cell in &grid.cells {
        let (x, y, z) = grid.cell_to_world(cell.col, cell.row, cell.height_offset.unwrap_or(0.0));
        tiles_by_type
            .entry(cell.tile_type.as_str())
            .or_default()
            .push((x, y, z));
    }

    writeln!(
        out,
        "using UnityEngine;\n\
using UnityEditor;\n\
using System.Collections.Generic;\n\
\n\
/// <summary>\n\
/// Auto-generated by grid2scene. Attach to an empty GameObject and use the\n\
/// \"Build Level\" button in the Inspector to construct the grid layout.\n\
/// Re-generation is idempotent: previously generated children are removed first.\n\
/// </summary>\n\
public class AlienBaseLevelBuilder : MonoBehaviour\n\
{{\n\
    [Header(\"Root settings\")]\n\
    public string generatedTag = \"Grid2SceneGenerated\";\n\
\n\
    [ContextMenu(\"Build Level\")]\n\
    public void BuildLevel()\n\
    {{\n\
        Undo.RegisterFullObjectHierarchyUndo(gameObject, \"Build Alien Base Level\");\n\
        ClearPrevious();\n\
        BuildTiles();\n\
        BuildSpawns();\n\
        BuildWeaponPickups();\n\
        BuildHazards();\n\
        BuildObjectives();\n\
    }}\n\
\n\
    private void ClearPrevious()\n\
    {{\n\
        var toDestroy = new List<GameObject>();\n\
        foreach (Transform child in transform)\n\
        {{\n\
            if (child.CompareTag(generatedTag))\n\
            {{\n\
                toDestroy.Add(child.gameObject);\n\
            }}\n\
        }}\n\
        foreach (var go in toDestroy)\n\
        {{\n\
            Undo.DestroyObjectImmediate(go);\n\
        }}\n\
    }}\n"
    )?;

    // Tiles: generate a method that instantiates prefabs per tile_type.
    writeln!(out, "    private void BuildTiles()\n    {{")?;
    writeln!(out, "        GameObject parent = new GameObject(\"Tiles\");")?;
    writeln!(out, "        parent.transform.SetParent(transform, false);")?;
    writeln!(out, "        parent.tag = generatedTag;")?;

    // Map tile_type -> prefab path from tileset.
    writeln!(out, "        // Tile prefabs\n")?;
    for tile_mapping in &tileset.tile_mappings {
        writeln!(
            out,
            "        // tile_type: {tile}\n\
        {{\n\
            string prefabPath = \"{prefab_path}\";\n\
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);\n\
            if (prefab == null)\n\
            {{\n\
                Debug.LogWarning($\"Missing prefab for tile_type {tile} at '{{prefabPath}}'\");\n\
            }}\n\
            else\n\
            {{\n\
                var positions = new Vector3[]\n\
                {{",
            tile = tile_mapping.tile_type,
            prefab_path = tile_mapping.asset_id
        )?;
        if let Some(instances) = tiles_by_type.get(tile_mapping.tile_type.as_str()) {
            for (x, y, z) in instances {
                writeln!(out, "                    new Vector3({:.3}f, {:.3}f, {:.3}f),", x, y, z)?;
            }
        }
        writeln!(
            out,
            "                }};\n\
                foreach (var pos in positions)\n\
                {{\n\
                    var instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab);\n\
                    Undo.RegisterCreatedObjectUndo(instance, \"Create tile\");\n\
                    instance.transform.position = pos;\n\
                    instance.transform.SetParent(parent.transform, true);\n\
                    instance.tag = generatedTag;\n\
                }}\n\
            }}\n\
        }}\n"
        )?;
    }
    writeln!(out, "    }}\n")?;

    // Spawn points
    writeln!(out, "    private void BuildSpawns()\n    {{")?;
    let spawn_prefab = &tileset.entity_mappings.spawn.prefaborclass;
    writeln!(
        out,
        "        string spawnPrefabPath = \"{path}\";\n\
        var spawnPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(spawnPrefabPath);\n\
        if (spawnPrefab == null)\n\
        {{\n\
            Debug.LogWarning($\"Missing spawn prefab at '{{spawnPrefabPath}}'\");\n\
            return;\n\
        }}\n\
        var parent = new GameObject(\"Spawns\");\n\
        parent.transform.SetParent(transform, false);\n\
        parent.tag = generatedTag;\n",
        path = spawn_prefab
    )?;
    for sp in &entities.spawn_points {
        let (x, y, z) = grid.cell_to_world(sp.col, sp.row, sp.y_offset.unwrap_or(0.0));
        let yaw = sp.facing_deg.unwrap_or(0.0);
        writeln!(
            out,
            "        {{\n\
            var instance = (GameObject)PrefabUtility.InstantiatePrefab(spawnPrefab);\n\
            Undo.RegisterCreatedObjectUndo(instance, \"Create spawn\");\n\
            instance.name = \"Spawn_{id}\";\n\
            instance.transform.position = new Vector3({:.3}f, {:.3}f, {:.3}f);\n\
            instance.transform.rotation = Quaternion.Euler(0.0f, {:.3}f, 0.0f);\n\
            instance.transform.SetParent(parent.transform, true);\n\
            instance.tag = generatedTag;\n\
        }}\n",
            x,
            y,
            z,
            yaw,
            id = sp.id
        )?;
    }
    writeln!(out, "    }}\n")?;

    // Weapon pickups
    writeln!(out, "    private void BuildWeaponPickups()\n    {{")?;
    writeln!(
        out,
        "        var parent = new GameObject(\"WeaponPickups\");\n\
        parent.transform.SetParent(transform, false);\n\
        parent.tag = generatedTag;\n"
    )?;
    writeln!(out, "        // weapon_type -> prefab path\n")?;
    for (weapon_type, prefab_path) in &tileset.entity_mappings.weapon_pickup {
        writeln!(
            out,
            "        BuildWeaponPickupGroup(\"{weapon}\", \"{path}\", parent);\n",
            weapon = weapon_type,
            path = prefab_path
        )?;
    }
    writeln!(out, "    }}\n")?;

    // Helper for weapon groups
    writeln!(
        out,
        "    private void BuildWeaponPickupGroup(string weaponType, string prefabPath, GameObject parent)\n    {{\n\
        var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);\n\
        if (prefab == null)\n\
        {{\n\
            Debug.LogWarning($\"Missing weapon pickup prefab for '{{weaponType}}' at '{{prefabPath}}'\");\n\
            return;\n\
        }}\n"
    )?;
    writeln!(out, "        var positions = new List<(string id, Vector3 pos)>();")?;
    for w in &entities.weapon_pickups {
        let (x, y, z) = grid.cell_to_world(w.col, w.row, w.y_offset.unwrap_or(0.0));
        writeln!(
            out,
            "        if (weaponType == \"{ty}\") positions.Add((\"{id}\", new Vector3({:.3}f, {:.3}f, {:.3}f)));",
            x,
            y,
            z,
            ty = w.weapon_type,
            id = w.id
        )?;
    }
    writeln!(
        out,
        "\n\
        foreach (var entry in positions)\n\
        {{\n\
            var instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab);\n\
            Undo.RegisterCreatedObjectUndo(instance, \"Create weapon pickup\");\n\
            instance.name = $\"Pickup_{ '{' }entry.id{ '}' }\";\n\
            instance.transform.position = entry.pos;\n\
            instance.transform.SetParent(parent.transform, true);\n\
            instance.tag = generatedTag;\n\
        }}\n\
    }}\n"
    )?;

    // Hazards and Objectives can follow the same pattern; for brevity we show one each.
    writeln!(
        out,
        "    private void BuildHazards()\n    {{\n\
        var parent = new GameObject(\"Hazards\");\n\
        parent.transform.SetParent(transform, false);\n\
        parent.tag = generatedTag;\n"
    )?;
    for (haz_type, prefab_path) in &tileset.entity_mappings.hazard_volume {
        writeln!(
            out,
            "        BuildHazardGroup(\"{ty}\", \"{path}\", parent);\n",
            ty = haz_type,
            path = prefab_path
        )?;
    }
    writeln!(out, "    }}\n")?;

    writeln!(
        out,
        "    private void BuildHazardGroup(string hazardType, string prefabPath, GameObject parent)\n    {{\n\
        var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);\n\
        if (prefab == null)\n\
        {{\n\
            Debug.LogWarning($\"Missing hazard prefab for '{{hazardType}}' at '{{prefabPath}}'\");\n\
            return;\n\
        }}\n\
        var entries = new List<(string id, Vector3 center, float radius, float ymin, float ymax)>();\n"
    )?;
    for h in &entities.hazard_volumes {
        let (cx, cy, cz) =
            grid.cell_to_world(h.center_col.unwrap_or(0), h.center_row.unwrap_or(0), 0.0);
        let radius_world = h.radius_cells.unwrap_or(0.0) * grid.cell_size;
        let ymin = grid.y_level + h.min_y_offset.unwrap_or(0.0);
        let ymax = grid.y_level + h.max_y_offset.unwrap_or(0.0);
        writeln!(
            out,
            "        if (hazardType == \"{ty}\") entries.Add((\"{id}\", new Vector3({:.3}f, {:.3}f, {:.3}f), {:.3}f, {:.3}f, {:.3}f));",
            cx,
            cy,
            cz,
            radius_world,
            ymin,
            ymax,
            ty = h.hazard_type,
            id = h.id
        )?;
    }
    writeln!(
        out,
        "\n\
        foreach (var e in entries)\n\
        {{\n\
            var instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab);\n\
            Undo.RegisterCreatedObjectUndo(instance, \"Create hazard\");\n\
            instance.name = $\"Hazard_{ '{' }e.id{ '}' }\";\n\
            instance.transform.position = e.center;\n\
            instance.transform.SetParent(parent.transform, true);\n\
            instance.tag = generatedTag;\n\
            // TODO: configure collider size from radius/ymin/ymax\n\
        }}\n\
    }}\n"
    )?;

    // Objectives
    writeln!(
        out,
        "    private void BuildObjectives()\n    {{\n\
        var parent = new GameObject(\"Objectives\");\n\
        parent.transform.SetParent(transform, false);\n\
        parent.tag = generatedTag;\n"
    )?;
    for (obj_type, prefab_path) in &tileset.entity_mappings.objective {
        writeln!(
            out,
            "        BuildObjectiveGroup(\"{ty}\", \"{path}\", parent);\n",
            ty = obj_type,
            path = prefab_path
        )?;
    }
    writeln!(out, "    }}\n")?;

    writeln!(
        out,
        "    private void BuildObjectiveGroup(string objectiveType, string prefabPath, GameObject parent)\n    {{\n\
        var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);\n\
        if (prefab == null)\n\
        {{\n\
            Debug.LogWarning($\"Missing objective prefab for '{{objectiveType}}' at '{{prefabPath}}'\");\n\
            return;\n\
        }}\n\
        var entries = new List<(string id, Vector3 pos)>();\n"
    )?;
    for o in &entities.objectives {
        let (x, y, z) = grid.cell_to_world(o.col, o.row, o.y_offset.unwrap_or(0.0));
        writeln!(
            out,
            "        if (objectiveType == \"{ty}\") entries.Add((\"{id}\", new Vector3({:.3}f, {:.3}f, {:.3}f)));",
            x,
            y,
            z,
            ty = o.objective_type,
            id = o.id
        )?;
    }
    writeln!(
        out,
        "\n\
        foreach (var e in entries)\n\
        {{\n\
            var instance = (GameObject)PrefabUtility.InstantiatePrefab(prefab);\n\
            Undo.RegisterCreatedObjectUndo(instance, \"Create objective\");\n\
            instance.name = $\"Objective_{ '{' }e.id{ '}' }\";\n\
            instance.transform.position = e.pos;\n\
            instance.transform.SetParent(parent.transform, true);\n\
            instance.tag = generatedTag;\n\
        }}\n\
    }}\n\
}}\n"
    )?;

    Ok(())
}
