use std::io::Write;

use anyhow::Result;

use crate::model::{Entities, Grid, Tileset};

pub fn emit(
    grid: &Grid,
    entities: &Entities,
    tileset: &Tileset,
    mut out: impl Write,
) -> Result<()> {
    // Group floor/wall cells by tile_type for ISM batching.
    let mut tiles_by_type: std::collections::BTreeMap<&str, Vec<(f32, f32, f32)>> =
        std::collections::BTreeMap::new();

    for cell in &grid.cells {
        let (x, y, z) = grid.cell_to_world(cell.col, cell.row, cell.height_offset.unwrap_or(0.0));
        tiles_by_type
            .entry(cell.tile_type.as_str())
            .or_default()
            .push((x, y, z));
    }

    writeln!(
        out,
        "import unreal\n\n\
from math import radians\n\n\
# Auto-generated by grid2scene. Re-run safely; it will clean up old instances.\n\
def build_level():\n\
    editor_level_lib = unreal.EditorLevelLibrary()\n\
    editor_asset_lib = unreal.EditorAssetLibrary()\n\
    subsystem = unreal.EditorActorSubsystem()\n\
    world = editor_level_lib.get_editor_world()\n\
\n\
    # Delete previously generated actors with this tag.\n\
    for actor in subsystem.get_all_level_actors():\n\
        tags = [str(t) for t in actor.tags]\n\
        if 'Grid2SceneGenerated' in tags:\n\
            subsystem.destroy_actor(actor)\n\
\n\
    # Create a root actor to parent everything generated by this script.\n\
    root_actor = editor_level_lib.spawn_actor_from_class(\n\
        unreal.EmptyActor, unreal.Vector(0.0, 0.0, 0.0)\n\
    )\n\
    root_actor.set_actor_label('Grid2SceneRoot')\n\
    root_actor.tags.append('Grid2SceneGenerated')\n"
    )?;

    // Tiles (ISM components)
    writeln!(out, "    # Tile ISM components\n")?;
    for tile_mapping in &tileset.tile_mappings {
        if let Some(instances) = tiles_by_type.get(tile_mapping.tile_type.as_str()) {
            writeln!(
                out,
                "    # tile_type: {tile}\n\
    mesh_asset = editor_asset_lib.load_asset('{mesh}')\n\
    ism_comp = unreal.InstancedStaticMeshComponent(root_actor)\n\
    ism_comp.set_static_mesh(mesh_asset)\n\
    ism_comp.set_mobility(unreal.ComponentMobility.STATIC)\n\
    ism_comp.register_component()\n\
    root_actor.add_instance_component(ism_comp)\n",
                tile = tile_mapping.tile_type,
                mesh = tile_mapping.asset_id
            )?;

            writeln!(out, "    for x, y, z in [")?;
            for (x, y, z) in instances {
                writeln!(out, "        ({:.3}, {:.3}, {:.3}),", x, y, z)?;
            }
            writeln!(
                out,
                "    ]:\n\
        transform = unreal.Transform(\n\
            translation=unreal.Vector(x, y, z),\n\
            rotation=unreal.Rotator(0.0, 0.0, 0.0),\n\
            scale3d=unreal.Vector(1.0, 1.0, 1.0)\n\
        )\n\
        ism_comp.add_instance(transform)\n"
            )?;
        }
    }

    // Spawns
    writeln!(out, "    # Player spawn points\n")?;
    let spawn_class = &tileset.entity_mappings.spawn.prefaborclass;
    writeln!(
        out,
        "    spawn_class = editor_asset_lib.load_asset('{classpath}')\n",
        classpath = spawn_class
    )?;
    writeln!(out, "    for data in [")?;
    for sp in &entities.spawn_points {
        let (x, y, z) = grid.cell_to_world(sp.col, sp.row, sp.y_offset.unwrap_or(0.0));
        let yaw = sp.facing_deg.unwrap_or(0.0);
        writeln!(
            out,
            "        dict(id='{id}', x={:.3}, y={:.3}, z={:.3}, yaw={:.3}),",
            x,
            y,
            z,
            yaw,
            id = sp.id
        )?;
    }
    writeln!(
        out,
        "    ]:\n\
        actor = editor_level_lib.spawn_actor_from_class(\n\
            spawn_class,\n\
            unreal.Vector(data['x'], data['y'], data['z']),\n\
            unreal.Rotator(0.0, data['yaw'], 0.0)\n\
        )\n\
        actor.set_actor_label(f\"Spawn_{'{'}data['id']{'}'}\")\n\
        actor.tags.append('Grid2SceneGenerated')\n"
    )?;

    // Weapon pickups
    writeln!(out, "    # Weapon pickups\n")?;
    writeln!(out, "    weapon_map = {{")?;
    for (weapon_type, class_path) in &tileset.entity_mappings.weapon_pickup {
        writeln!(
            out,
            "        '{ty}': '{path}',",
            ty = weapon_type,
            path = class_path
        )?;
    }
    writeln!(
        out,
        "    }}\n\
    for data in ["
    )?;
    for w in &entities.weapon_pickups {
        let (x, y, z) = grid.cell_to_world(w.col, w.row, w.y_offset.unwrap_or(0.0));
        writeln!(
            out,
            "        dict(id='{id}', weapon_type='{ty}', x={:.3}, y={:.3}, z={:.3}),",
            x,
            y,
            z,
            id = w.id,
            ty = w.weapon_type
        )?;
    }
    writeln!(
        out,
        "    ]:\n\
        class_path = weapon_map.get(data['weapon_type'])\n\
        if not class_path:\n\
            unreal.log_warning(f\"Unknown weapon_type { '{' }data['weapon_type']{ '}' } in tileset\")\n\
            continue\n\
        cls = editor_asset_lib.load_asset(class_path)\n\
        actor = editor_level_lib.spawn_actor_from_class(\n\
            cls,\n\
            unreal.Vector(data['x'], data['y'], data['z']),\n\
            unreal.Rotator(0.0, 0.0, 0.0)\n\
        )\n\
        actor.set_actor_label(f\"Pickup_{'{'}data['id']{'}'}\")\n\
        actor.tags.append('Grid2SceneGenerated')\n"
    )?;

    // Hazards
    writeln!(out, "    # Hazard volumes\n")?;
    writeln!(out, "    hazard_map = {{")?;
    for (haz_type, class_path) in &tileset.entity_mappings.hazard_volume {
        writeln!(
            out,
            "        '{ty}': '{path}',",
            ty = haz_type,
            path = class_path
        )?;
    }
    writeln!(
        out,
        "    }}\n\
    for data in ["
    )?;
    for h in &entities.hazard_volumes {
        let (cx, cy, cz) =
            grid.cell_to_world(h.center_col.unwrap_or(0), h.center_row.unwrap_or(0), 0.0);
        let radius_world = h.radius_cells.unwrap_or(0.0) * grid.cell_size;
        let ymin = grid.y_level + h.min_y_offset.unwrap_or(0.0);
        let ymax = grid.y_level + h.max_y_offset.unwrap_or(0.0);
        writeln!(
            out,
            "        dict(id='{id}', hazard_type='{ty}', cx={:.3}, cy={:.3}, cz={:.3}, radius={:.3}, ymin={:.3}, ymax={:.3}),",
            cx,
            cy,
            cz,
            radius_world,
            ymin,
            ymax,
            id = h.id,
            ty = h.hazard_type
        )?;
    }
    writeln!(
        out,
        "    ]:\n\
        class_path = hazard_map.get(data['hazard_type'])\n\
        if not class_path:\n\
            unreal.log_warning(f\"Unknown hazard_type { '{' }data['hazard_type']{ '}' } in tileset\")\n\
            continue\n\
        cls = editor_asset_lib.load_asset(class_path)\n\
        actor = editor_level_lib.spawn_actor_from_class(\n\
            cls,\n\
            unreal.Vector(data['cx'], data['cy'], data['cz']),\n\
            unreal.Rotator(0.0, 0.0, 0.0)\n\
        )\n\
        actor.set_actor_label(f\"Hazard_{'{'}data['id']{'}'}\")\n\
        actor.tags.append('Grid2SceneGenerated')\n\
        # TODO: configure volume radius/height via a custom component or Blueprint API\n"
    )?;

    // Objectives
    writeln!(out, "    # Objectives\n")?;
    writeln!(out, "    objective_map = {{")?;
    for (obj_type, class_path) in &tileset.entity_mappings.objective {
        writeln!(
            out,
            "        '{ty}': '{path}',",
            ty = obj_type,
            path = class_path
        )?;
    }
    writeln!(
        out,
        "    }}\n\
    for data in ["
    )?;
    for o in &entities.objectives {
        let (x, y, z) = grid.cell_to_world(o.col, o.row, o.y_offset.unwrap_or(0.0));
        writeln!(
            out,
            "        dict(id='{id}', objective_type='{ty}', x={:.3}, y={:.3}, z={:.3}),",
            x,
            y,
            z,
            id = o.id,
            ty = o.objective_type
        )?;
    }
    writeln!(
        out,
        "    ]:\n\
        class_path = objective_map.get(data['objective_type'])\n\
        if not class_path:\n\
            unreal.log_warning(f\"Unknown objective_type { '{' }data['objective_type']{ '}' } in tileset\")\n\
            continue\n\
        cls = editor_asset_lib.load_asset(class_path)\n\
        actor = editor_level_lib.spawn_actor_from_class(\n\
            cls,\n\
            unreal.Vector(data['x'], data['y'], data['z']),\n\
            unreal.Rotator(0.0, 0.0, 0.0)\n\
        )\n\
        actor.set_actor_label(f\"Objective_{'{'}data['id']{'}'}\")\n\
        actor.tags.append('Grid2SceneGenerated')\n\
\n\
if __name__ == '__main__':\n\
    build_level()\n"
    )?;

    Ok(())
}
