//! Asset hasher crate for grid2scene.
//! 
//! Computes a deterministic hash (Blake3) of all tileset textures, models, and audio files
//! listed in the map manifest. The hash is embedded in the generated scene as a comment
//! to assist with cache invalidation and asset versioning.

use blake3::Hasher;
use std::fs::File;
use std::io::{BufReader, Read};
use std::path::{Path, PathBuf};

/// Computes a Blake3 hash of a single file.
pub fn hash_file(path: &Path) -> Result<blake3::Hash, std::io::Error> {
    let file = File::open(path)?;
    let mut reader = BufReader::new(file);
    let mut hasher = Hasher::new();
    
    let mut buffer = vec![0u8; 8192];
    loop {
        let bytes_read = reader.read(&mut buffer)?;
        if bytes_read == 0 {
            break;
        }
        hasher.update(&buffer[..bytes_read]);
    }
    
    Ok(hasher.finalize())
}

/// Computes a combined hash of multiple asset files.
pub fn hash_assets(paths: &[PathBuf]) -> Result<String, std::io::Error> {
    let mut combined_hasher = Hasher::new();
    
    // Sort paths for deterministic ordering
    let mut sorted_paths = paths.to_vec();
    sorted_paths.sort();
    
    for path in &sorted_paths {
        match hash_file(path) {
            Ok(hash) => {
                // Combine individual file hashes into the combined hash
                combined_hasher.update(hash.as_bytes());
            }
            Err(e) => {
                eprintln!("Warning: Failed to hash file {:?}: {}", path, e);
                // Continue with other files
            }
        }
    }
    
    Ok(combined_hasher.finalize().to_string())
}

/// Generates a comment string containing the asset hash for embedding in generated scene files.
pub fn generate_asset_hash_comment(hash: &str) -> String {
    format!(
        "// Asset Hash: {}\n// Generated by grid2scene asset-hasher\n// Use this hash for cache invalidation and asset versioning",
        hash
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::tempdir;

    #[test]
    fn test_hash_file() {
        let dir = tempdir().unwrap();
        let file_path = dir.path().join("test.txt");
        
        let mut file = File::create(&file_path).unwrap();
        file.write_all(b"hello world").unwrap();
        
        let hash = hash_file(&file_path).unwrap();
        assert!(!hash.as_bytes().iter().all(|&b| b == 0));
    }

    #[test]
    fn test_hash_assets_deterministic() {
        let dir = tempdir().unwrap();
        let file1 = dir.path().join("a.txt");
        let file2 = dir.path().join("b.txt");
        
        let mut f1 = File::create(&file1).unwrap();
        f1.write_all(b"content a").unwrap();
        let mut f2 = File::create(&file2).unwrap();
        f2.write_all(b"content b").unwrap();
        
        let paths1 = vec![file1.clone(), file2.clone()];
        let paths2 = vec![file2.clone(), file1.clone()]; // Different order
        
        let hash1 = hash_assets(&paths1).unwrap();
        let hash2 = hash_assets(&paths2).unwrap();
        
        // Should be the same regardless of input order
        assert_eq!(hash1, hash2);
    }

    #[test]
    fn test_generate_comment() {
        let comment = generate_asset_hash_comment("abc123");
        assert!(comment.contains("abc123"));
        assert!(comment.contains("asset-hasher"));
    }
}
